version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
      - /home/ilker/miniconda3/envs/vehicle-type-detection-api:/opt/conda/envs/vehicle-type-detection-api:ro  # Mount conda environment as read-only
    environment:
      - PYTHONPATH=/opt/conda/envs/vehicle-type-detection-api/lib/python3.12/site-packages
    env_file:
      - .env.dev
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
